// client/src/components/Home/Table/TableItem.svelte
<script>
    import { goto } from '$app/navigation';
// @ts-nocheck  
    export let concept, amount, date, type, id;
    const edit = () => {
        goto(`/edit/${id}`)
    }
</script>

<tr>
    <td>{`${date.getDate()}-${date.getMonth()+1}-${date.getFullYear()}`}</td>
    <td>{type}</td>
    <td>{concept}</td>  
    <td>{amount}</td>
    <td><button on:click={edit}>Editar</button><button>Eliminar</button></td>
    
</tr>
<style>

</style>

// client/src/components/Dashboard/Table/TableItem.jsx
import React, { useEffect, useState } from 'react'
import { convertDateToStriing } from '../../../helpers/helpers'
export default function TableItem({operation}) {
  if(operation){
    const date = convertDateToStriing(operation.date)
    return (
        <tr id={operation._id}>
            <td>{date}</td>
            <td>{operation.type}</td>
            <td>{operation.concept}</td>  
            <td>{operation.amount}</td>
            <td><a href={`edit/${operation._id}&${operation.type}`}><button>Editar</button></a><button className='delete-button'>Eliminar</button></td>
        </tr>
      )
  }
}
